/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "indiaPostRed": "#E63329",
        "surface-bright": "#343949",
        "on-primary": "#690002",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline": "#ac8883",
        "on-secondary-container": "#e6ecff",
        "inverse-on-surface": "#2b3040",
        "surface-container-highest": "#2f3445",
        "primary-fixed": "#ffdad5",
        "secondary-fixed": "#d8e2ff",
        "inverse-surface": "#dee1f7",
        "background": "#0e1322",
        "on-secondary-fixed": "#001a42",
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "surface-tint": "#ffb4a9",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary": "#002e6a",
        "error": "#ffb4ab",
        "surface": "#0e1322",
        "primary": "#ffb4a9",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-container": "#00a572",
        "on-primary-fixed-variant": "#930005",
        "surface-container-high": "#25293a",
        "on-tertiary": "#003824",
        "tertiary-fixed-dim": "#4edea3",
        "error-container": "#93000a",
        "inverse-primary": "#bd0f10",
        "on-primary-container": "#5c0002",
        "primary-fixed-dim": "#ffb4a9",
        "surface-variant": "#2f3445",
        "primary-container": "#ff5545",
        "on-background": "#dee1f7",
        "secondary-container": "#0566d9",
        "on-tertiary-fixed-variant": "#005236",
        "secondary": "#adc6ff",
        "on-surface": "#dee1f7",
        "surface-container": "#1a1f2f",
        "on-surface-variant": "#e5bdb8",
        "surface-dim": "#0e1322",
        "on-tertiary-container": "#00311f",
        "surface-container-low": "#161b2b",
        "on-primary-fixed": "#410001",
        "surface-container-lowest": "#090e1c",
        "outline-variant": "#5c403c"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "technical": ["IBM Plex Mono", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
